Microsoft_System = ['SystemIdleProcess', 'System', 'Registry', 'smss.exe', 'csrss.exe', 'wininit.exe',
                    'services.exe', 'lsass.exe', 'svchost.exe', 'fontdrvhost.exe', 'MemoryCompression',
                    'spoolsv.exe', 'CExecSvc.exe', 'VmComputeAgent.exe', 'MoUsoCoreWorker.exe', 'winlogon.exe',
                    'WUDFHost.exe', 'dwm.exe', 'rdpclip.exe', 'sihost.exe', 'taskhostw.exe', 'ctfmon.exe',
                    'rdpinput.exe', 'explorer.exe', 'TabTip.exe', 'backgroundTaskHost.exe', 'RuntimeBroker.exe',
                    'smartscreen.exe', 'SearchApp.exe', 'TextInputHost.exe', 'dllhost.exe', 'cmd.exe',
                    'conhost.exe', 'BackgroundTransferHost.ex', 'WmiPrvSE.exe', 'WMIADAP.exe', 'tasklist.exe',
                    'SecureSystem', 'omadmclient.exe', 'omadmprc.exe']
Known_Good = ["chrome.exe", "notepad.exe", "OneDrive.exe", "Cortana.exe", "ONENOTEM.EXE", "GoogleCrashHandler.exe",
              "GoogleCrashHandler64.exe", "PowerMgr.exe", "LsaIso.exe", "igfxCUIServiceN.exe", "vmms.exe",
              "ibmpmsvc.exe", "ETDService.exe", "wlanext.exe", "IntelCpHDCPSvc.exe", "armsvc.exe", "DAX3API.exe",
              "vmcompute.exe", "OfficeClickToRun.exe", 'OneApp.IGCC.WinService.ex', 'esif_uf.exe',
              'IntelAudioService.exe', 'SmartStandby.exe', 'LMS.exe', 'WBFResetService108.exe',
              'RtkAudUService64.exe', 'TbtP2pShortcutService.exe', 'tphkload.exe', 'MsMpEng.exe',
              'WMIRegistrationService.ex', 'jhi_service.exe', 'ETDCtrl.exe', 'igfxEMN.exe', 'tposd.exe',
              'shtctky.exe', 'StartMenuExperienceHost.e', 'NisSrv.exe', 'SearchIndexer.exe', 'vmmem',
              'SearchFilterHost.exe', 'SearchProtocolHost.exe', 'Calculator.exe', 'fsnotifier.exe', 'pycharm64.exe',
              'FileCoAuth.exe', 'Microsoft.Photos.exe', 'PhoneExperienceHost.exe', 'SamsungPortableSSDMon_1.0',
              'SecurityHealthSystray.exe', 'SecurityHealthService.exe', 'ApplicationFrameHost.exe',
              'SystemSettings.exe', 'UserOOBEBroker.exe', 'ShellExperienceHost.exe', 'LockApp.exe', 'Music.UI.exe',
              'GameBar.exe', 'audiodg.exe', 'igfxextN.exe', 'dasHost.exe', 'GameBarFTServer.exe',
              'LocationNotificationWindo', 'HxTsr.exe', 'mmc.exe', 'TrustedInstaller.exe', 'TiWorker.exe',
              'SgrmBroker.exe', 'mstsc.exe', 'IntelCpHeciSvc.exe', 'igfxCUIService.exe', 'RtkAudioService64.exe',
              'RAVBg64.exe', 'igfxEM.exe', 'YourPhone.exe', 'RtkNGUI64.exe', 'WavesSvc64.exe',
              'SystemSettingsBroker.exe', 'LogonUI.exe', 'MusNotifyIcon.exe', 'msedge.exe', 'MpCmdRun.exe',
              'Skype.exe', 'UsefulTools.exe', 'Microsoft.SharePoint.exe', 'GoogleUpdate.exe',
              'MicrosoftEdgeUpdate.exe', 'msiexec.exe', 'Lenovo.Modern.ImControlle', 'LenovoVantageService.exe',
              'LNBITSSvc.exe', 'LenovoUtilityService.exe', 'RstMwService.exe', 'gamingservicesnet.exe',
              'gamingservices.exe', 'FnHotkeyUtility.exe', 'SUPERAntiSpyware.exe', 'SASCore64.exe',
              'LenovoVantage-(LenovoComp', 'LenovoVantage-(LenovoBoos', 'LenovoVantage-(LenovoServ',
              'LenovoVantage-(DeviceSett', 'HxOutlook.exe', 'WWAHost.exe', 'yuja-software-capture-ser',
              'yuja-restart-service.exe', 'SocketHeciServer.exe', 'aesm_service.exe', 'LenovoVantage-(VantageCor',
              'SurfaceDisplayColorServic', 'WINWORD.EXE', 'EXCEL.EXE', 'Teams.exe', 'Taskmgr.exe', 'SpeechRuntime.exe',
              'SurfaceService.exe', 'AppVShNotify.exe', 'ELANFPService.exe', 'CompPkgSrv.exe', 'MpCopyAccelerator.exe',
              'splwow64.exe', 'XboxGameBarSpotify.exe']
Known_Flags = {"python.exe": 72,
               "LITSSvc.exe": 49,
               "FMService64.exe": 64,
               "pservice.exe": 57,
               "CTskMstr.exe": 46,
               "parsecd.exe": 56,
               "AutoModeDetect.exe": 50,
               'msdtc.exe': 89
               }
Known_Bad = ["unsecapp.exe", 'popnet.exe']